-- Seed / sanity-check script for `vocabulary`
--
-- Goal:
-- - `word` = English (what the user types in English)
-- - `word_target` = the local language word/phrase (Tok Pisin / Motu / etc.)
-- - `translation` = keep as English gloss/meaning (can be same as `word` if you don't have a longer gloss yet)
--
-- 1) Find language IDs:
-- SELECT language_id, name FROM language;
--
-- 2) Insert vocabulary (replace language_id values accordingly):
-- Example: English -> Tok Pisin
-- INSERT INTO vocabulary (word_target, word, translation, language_id)
-- VALUES ('moning', 'good morning', 'good morning', 1);
--
-- Example: English -> Motu
-- INSERT INTO vocabulary (word_target, word, translation, language_id)
-- VALUES ('Ena bega', 'good morning', 'good morning', 2);
--
-- 3) Verify lookup works (English -> local):
-- SELECT vocab_id, word, word_target, translation, language_id
-- FROM vocabulary
-- WHERE LOWER(word) = 'good morning';
